# ------------------------------------------------------------------------------
#          -= Arno's (NFT) Firewall(ANF) - arno-fwfilter configuration =-
# ------------------------------------------------------------------------------
# Settings for arno-fwfilter (the firewall log filter). Command line options
# override these settings, see "arno-fwfilter --help".
# ------------------------------------------------------------------------------

# Resolve IP adresses to names (requires "dig"). Without a name the IP is shown
RESOLVE_NAMES=1

# (Try to) obtain the geographical location of the IPs (can be very slow!)
SHOW_LOCATION=0

# Use ANSI colors (increases readability)
USE_ANSI_COLORS=1

# Format the output as (colored) HTML (for emails etc.)
USE_HTML=0

# Put all information about an event on a single line
USE_1ROW=0
